// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCPiJXaFyFRCdmGivt3xynY46GN1MxNjH0',
    appId: '1:406917869237:web:e5e1a52ea91eba04ab98fc',
    messagingSenderId: '406917869237',
    projectId: 'journease-7f1d5',
    authDomain: 'journease-7f1d5.firebaseapp.com',
    storageBucket: 'journease-7f1d5.firebasestorage.app',
    measurementId: 'G-TF9QLM3689',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCOriF_TX5_oIqzJT9qcNa_t0pSLpSx0t4',
    appId: '1:406917869237:android:8adf4073963f9aa2ab98fc',
    messagingSenderId: '406917869237',
    projectId: 'journease-7f1d5',
    storageBucket: 'journease-7f1d5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBpckXGRzUgVhCv-ha6HHofau4W5HxsW6Y',
    appId: '1:406917869237:ios:27a4bb64b9dea2beab98fc',
    messagingSenderId: '406917869237',
    projectId: 'journease-7f1d5',
    storageBucket: 'journease-7f1d5.firebasestorage.app',
    iosBundleId: 'com.example.jurnease',
  );
}
